
# starts 4 docker containers running minio server instances.
# using nginx reverse proxy, load balancing, you can access
# it through port 9000.
services:

  code:
    build:
      context: .
    container_name: code
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - DOCKER_USER=$USER
      - SUDO_PASSWORD=password
      - NVIDIA_VISIBLE_DEVICES=0
      - NVIDIA_DRIVER_CAPABILITIES=all
      - DEFAULT_WORKSPACE=/config/workspace
      - VIRTUAL_ENV=/opt/venv
      - PORT=28080
      #- CUDA_VISIBLE_DEVICES=0
    restart: "always"
    shm_size: 6gb
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    volumes:
      - .:/config/workspace
      - ${HOME}/.ssh/:/.ssh
    ports:
      - 28080:28080
