[project]
name = "training"
version = "0.1.0"
description = "Module which provides logic to train various models with data in the chosen infrastructure"
readme = "README.md"
requires-python = ">=3.12"
<<<<<<< HEAD
dependencies = [
    "torch<2.3; sys_platform == 'darwin' and platform_machine == 'x86_64'",
    "torch; sys_platform != 'darwin' or platform_machine != 'x86_64'",
    "torchvision",
]

[tool.uv.sources]
torch = [
  { index = "pytorch-cu126", marker = "sys_platform == 'linux' or sys_platform == 'win32'" },
  { index = "pytorch-cpu", marker = "sys_platform == 'darwin'" },
]
torchvision = [
  { index = "pytorch-cu126", marker = "sys_platform == 'linux' or sys_platform == 'win32'" },
  { index = "pytorch-cpu", marker = "sys_platform == 'darwin'" },
]

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true


[[tool.uv.index]]
name = "pytorch-cu126"
url = "https://download.pytorch.org/whl/cu126"
explicit = true
=======
dependencies = []
>>>>>>> master
