[project]
name = "training"
version = "0.1.0"
description = "Module which provides logic to train various models with data in the chosen infrastructure"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []
