    name: Publish to PyPI

    on:
      release:
        types: [published] # Triggers when a new release is published

    jobs:
      deploy:
        runs-on: ubuntu-latest
        environment: terraform # If using a PyPI environment in GitHub Actions
        working-directory: ./scraping
        permissions:
          id-token: write # Required for PyPI Trusted Publishing
        steps:
          - uses: actions/checkout@v4
          - uses: astral-sh/setup-uv@v1 # Sets up uv
          - name: Build package
            run: uv build 
          - name: Publish package to PyPI
            run: uv publish # Or uv publish if using trusted publishing
            env:
              UV_PUBLISH_TOKEN: ${{ secrets.PYPI_TOKEN }} # Map GitHub secret to Terraform variable