name: Push Docker Images to ECR

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'opensora/**' # Trigger only on changes within this subdirectory
      - '.github/workflows/push.yml'
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Image
    environment: terraform 
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.REGION }}
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
    - name: Build and push
      uses: docker/build-push-action@v6
      working-directory: ./opensora
      with:
        context: .
        push: true
        tags: "$ECR_REGISTRY/$ECR_REPOSITORY:latest"
        cache-from: type=gha
        cache-to: type=gha,mode=max
        github-token: ${{ secrets.MY_CUSTOM_TOKEN }}
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: ${{ secrets.REGION }}
        IMAGE_TAG: latest
