name: Push Docker Images to ECR

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'opensora/**' # Trigger only on changes within this subdirectory
      - '.github/workflows/push.yml'
jobs:
  build:
    runs-on: self-hosted
    name: Build Image
    environment: terraform 
    steps:
    - name: Check out code
      uses: actions/checkout@v2
      
    - name: Install docker
      run: |
        apt-get update
        apt-get install docker
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.REGION }}
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        buildkitd-flags: --debug
    - name: Free up disk space
      uses: jlumbroso/free-disk-space@main
      with:
        # Optional: Configure options to specify what to remove
        # For example, to remove pre-cached tools:
        tools-cache: true
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: ./opensora
        push: true
        tags: "${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:latest"
        # cache-from: type=gha
        # cache-to: type=gha,mode=max
        # github-token: ${{ secrets.MY_CUSTOM_TOKEN }}
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: ${{ secrets.REGION }}
        IMAGE_TAG: latest
