name: Test

on:

  push:
    branches-ignore:
      - master  # Excludes the master branch
  pull_request:
    branches: 
      - master
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Enable UV
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
      - name: Install ruff
        run: uv tool install ruff@latest
      - name: Ruff lint
        run: uvx ruff check scraping/ video_generation/ opensora/
      - name: Ruff format
        run: uvx ruff format --diff scraping/ video_generation/ opensora/
      # This isn't a general Python lint, this style is just used in this repository
      - name: Prettier format
        run: npx prettier --prose-wrap always --check "*.md"
  # test:
  #   name: Run tests
  #   strategy:
  #     matrix:
  #       os: [ubuntu-latest, macos-latest, windows-latest]
  #   runs-on: ${{ matrix.os }}
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Enable UV
  #       uses: astral-sh/setup-uv@v5
  #       with:
  #         enable-cache: true
  #     - run: uv run --group dev pytest
