name: Test

on:

  push:

jobs:
  lint:
    if: ${{ github.event.pull_request.merged }}
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Enable UV
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
      - name: Ruff lint
        run: uv run --group lint ruff check .
      - name: Ruff format
        run: uv run --group lint ruff format --diff .
      # This isn't a general Python lint, this style is just used in this repository
      - name: Prettier format
        run: npx prettier --prose-wrap always --check "**/*.md"
  test:
    if: ${{ github.event.pull_request.merged }}
    name: Run tests
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Enable UV
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-local-path: "/path/to/cache"
      - run: uv run --group dev pytest